name: revoke-github-token

on: repository_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      SECRETS_CONTEXT_TOKEN: ${{secrets.GITHUB_TOKEN}}
      GITHUB_CONTEXT_TOKEN: ${{github.token}}
    steps:
    - run: |
        curl -v -X DELETE -H "Authorization: $SECRETS_CONTEXT_TOKEN" -H "Accept: application/vnd.github.gambit-preview+json" "https://api.github.com/installation/token"
    - run: |
        curl -v -X DELETE -H "Authorization: $GITHUB_CONTEXT_TOKEN" -H "Accept: application/vnd.github.gambit-preview+json" "https://api.github.com/installation/token"
